version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12  # Use a Python version matching your local setup
    steps:
      - checkout

      - run:
          name: Install curl
          command: |
            sudo apt-get update
            sudo apt-get install -y curl

      - run:
          name: Install uv
          command: |
            curl -Ls https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Confirm uv installed
          command: uv --version

      - run:
          name: Install dependencies using pyproject.toml
          command: |
            uv pip install .

      - run:
          name: Run tests with pytest
          command: pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
