version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout

      - run:
          name: Install curl
          command: |
            sudo apt-get update
            sudo apt-get install -y curl

      - run:
          name: Install uv
          command: |
            curl -Ls https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
            echo 'export VIRTUAL_ENV="$HOME/.venv"' >> $BASH_ENV
            echo 'export PATH="$VIRTUAL_ENV/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Create virtual environment
          command: |
            uv venv
            source $HOME/.venv/bin/activate

      - run:
          name: Install dependencies from pyproject.toml
          command: |
            source $HOME/.venv/bin/activate
            uv pip install .

      - run:
          name: Run tests
          command: |
            source $HOME/.venv/bin/activate
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
