version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout

      - run:
          name: Install curl
          command: |
            sudo apt-get update
            sudo apt-get install -y curl

      - run:
          name: Install uv
          command: |
            curl -Ls https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Create virtual environment in .venv
          command: |
            uv venv
            echo 'source .venv/bin/activate' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install dependencies from pyproject.toml
          command: |
            source .venv/bin/activate
            uv pip install .

      - run:
          name: Run tests
          command: |
            source .venv/bin/activate
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
